### ISSUE TITLE
Sayt tili

### ISSUE THREAD

**Issue by abdulatifkhan** [Ndn1618/temperature-convertor#2]
Sayt qaysi tilda yuritilsa, o'sha tilga to'g'irlab qo'yganimiz ma'qul(uzr, boshqa xato topolmadim)

![uz](https://user-images.githubusercontent.com/68887519/98636972-9ee00b80-2349-11eb-9ce7-3bfcae9b3e3c.jpg)

**Comment by udilbar** [comment]
To'g'irlab qo'ydik, rahmat )
